"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
APP = ['dj.py']
DATA_FILES = ['dj_kaldi.pmdl','microphone-results.wav','Microphone.py', 'newClient.py']
OPTIONS = {'argv_emulation': True,
           'plist': {
               'PyRuntimeLocations': [
                '/Users/pongpisit/anaconda3/lib/libpython3.6m.dylib'
               ]
           }}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
